### ISSUE TITLE
Package Bug? 

### ISSUE THREAD

**Issue by logan-markewich** [premAI-io/prem-python-sdk#16]
Getting a weird python error

```
llama-index-integrations/embeddings/llama-index-embeddings-premai/llama_index/embeddings/premai/base.py:13: in <module>
    from premai import Prem
E     File "/Users/loganmarkewich/.cache/pants/named_caches/pex_root/venvs/s/078b3051/venv/lib/python3.10/site-packages/premai/__init__.py", line 14
E       finetuning-admin: FinetuningAdminModule
E       ^^^^^^^^^^^^^^^^
E   SyntaxError: illegal target for annotation
```

Did something change? Seems like the latest package Is not valid python? Or at least, it breaks in python3.8, 3.9, and 3.10

**Comment by RussellLuo** [comment]
I found that this piece of code was submitted 10 hours ago by github-actions: https://github.com/premAI-io/prem-python-sdk/commit/c637b6b1d0f5e4c32f9ff455e56bf96034abef83.

**Comment by nsosio** [comment]
@logan-markewich thanks for reporting it, we are working on it

**Comment by allemonta** [comment]
@logan-markewich this bug will be fixed in the next deployment. You can use versions <= v0.3.41 for now

**Comment by logan-markewich** [comment]
Thanks @allemonta

**Comment by Anindyadeep** [comment]
Hi, I also got this similar issue
should't a quick be instead of writing `self.finetuning_admin` instead of writing `self.finetuning-admin`. 

Let me know if I need to put a quick fix on this on a PR, because langchain is also breaking due to this.  

cc: @nsosio
